### ISSUE TITLE
Could you add endpoint specification in settings?

### ISSUE THREAD

**Issue by masonfocus** [galihlprakoso/logseq-plugin-assistseq-ai-assistant#7]
Love your idea of this extension, could you add endpoint specification in settings? 

So that I can change say the base url of OpenAI from https://api.openai.com/v1/chat/completions to something else.

Now I can change the extension file to achieve that, but if you can enable changing it in the configs, it would be even better.

**Comment by galihlprakoso** [comment]
> Love your idea of this extension, could you add endpoint specification in settings?
> 
> So that I can change say the base url of OpenAI from https://api.openai.com/v1/chat/completions to something else.
> 
> Now I can change the extension file to achieve that, but if you can enable changing it in the configs, it would be even better.

Could you clarify which part of API you want to use other than chat completions? @masonfocus

**Comment by masonfocus** [comment]
> > Love your idea of this extension, could you add endpoint specification in settings?
> > So that I can change say the base url of OpenAI from https://api.openai.com/v1/chat/completions to something else.
> > Now I can change the extension file to achieve that, but if you can enable changing it in the configs, it would be even better.
> 
> Could you clarify which part of API you want to use other than chat completions? @masonfocus


I want to change the base part, for example, the perplexity api follows the openAI structure, if I can change the `https://api.openai.com/v1/` part to `https://api.perplexity.ai/`, I can use the perplexity api.

**Comment by galihlprakoso** [comment]
https://github.com/galihlprakoso/logseq-plugin-assistseq-ai-assistant/pull/9

Please feel free to reopen the issue if it's doesn't work as expected! @masonfocus
