### ISSUE TITLE
Unable to generate a visualization

### ISSUE THREAD

**Issue by drmandel01** [galihlprakoso/logseq-plugin-assistseq-ai-assistant#8]
...
service: notify.mobile_app_nothing data: message: "The alarm is triggered! Cause: {{open_sensors}}." title: Alert! data: ttl: 0 priority: high channel: alarm_stream color: "red"
...

Error 400: Error: Syntax error in graph: Parse error on line 84:
- NFC Tags (3) - bedroom, garage,

Expecting 'SPACELINE', 'NL', 'EOF', got 'SPACELIST'
Error: Parse error on line 84:
- NFC Tags (3) - bedroom, garage,
٨.
Expecting 'SPACELINE', 'NL', 'EOF', got 'SPACELIST'
at j.parseError (file:///usr/local/kroki/assets/mermaid/mindmap-definition-2aab62ef.js:69:17)
at j.parse (file:///usr/local/kroki/assets/mermaid/mindmap-definition-2aab62ef.js:94:214)
at ql.parse (file:///usr/local/kroki/assets/mermaid/mermaid-00886c59.js:6509:165)
at new ql (file:///usr/local/kroki/assets/mermaid/mermaid-00886c59.js:6501:161)
at fC (file:///usr/local/kroki/assets/mermaid/mermaid-00886c59.js:6532:10)
at async Object.Jb [as render] (file:///usr/local/kroki/assets/mermaid/mermaid-00886c59.js:7766:9)

**Comment by galihlprakoso** [comment]
> ... service: notify.mobile_app_nothing data: message: "The alarm is triggered! Cause: {{open_sensors}}." title: Alert! data: ttl: 0 priority: high channel: alarm_stream color: "red" ...
> 
> Error 400: Error: Syntax error in graph: Parse error on line 84:
> 
> * NFC Tags (3) - bedroom, garage,
> 
> Expecting 'SPACELINE', 'NL', 'EOF', got 'SPACELIST' Error: Parse error on line 84:
> 
> * NFC Tags (3) - bedroom, garage,
>   ٨.
>   Expecting 'SPACELINE', 'NL', 'EOF', got 'SPACELIST'
>   at j.parseError (file:///usr/local/kroki/assets/mermaid/mindmap-definition-2aab62ef.js:69:17)
>   at j.parse (file:///usr/local/kroki/assets/mermaid/mindmap-definition-2aab62ef.js:94:214)
>   at ql.parse (file:///usr/local/kroki/assets/mermaid/mermaid-00886c59.js:6509:165)
>   at new ql (file:///usr/local/kroki/assets/mermaid/mermaid-00886c59.js:6501:161)
>   at fC (file:///usr/local/kroki/assets/mermaid/mermaid-00886c59.js:6532:10)
>   at async Object.Jb [as render] (file:///usr/local/kroki/assets/mermaid/mermaid-00886c59.js:7766:9)

Can you give me the full visuzalization syntax? You can see it in the LogSeq's application local storage.. try to find values with key `chat-store` and try to see the visualization syntax. @drmandel01

**Comment by drmandel01** [comment]
I was unable to locate the files associated with application local storage and the related syntax.  I was able to query for a mermaid diagram with some other pages.  I am closing the comment.
